name: CI Zench - Continuous Benchmarking

on:
  push:
    branches: [dev]
    paths:
      - "zench/**"
      - "zench_examples/**"
      - "Cargo.toml"
      - "Cargo.lock"

  pull_request:
    branches: [dev, main, master]
    paths:
      - "zench/**"
      - "zench_examples/**"
      - "Cargo.toml"
      - "Cargo.lock"

env:
  CARGO_TERM_COLOR: always

jobs:
  multi_os_ci:
    strategy:
      matrix:
        # ---------------------------------
        # ubuntu-latest, windows-latest, macos-latest
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Rust manual
        run: rustup update && rustup component add clippy

      - name: Compute environment hash
        id: env_hash
        run: |
          HASH=$( (rustc --version; sha256sum Cargo.lock) | sha256sum | awk '{print $1}' )
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Restore Rust
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup/toolchains
            target/
            .zench_dummy
          key: zench-${{ runner.os }}-${{ steps.env_hash.outputs.hash }}

      - name: Make
        run: make github

      - name: Run release tests + benchmarks (if changed)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ZENCH=warn cargo test --release
          mkdir -p .zench_dummy

      - name: Run tests (no benchmarks)
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          cargo test
